k9s:
  cluster: arn:aws:eks:us-east-1:383410406325:cluster/eks-20240925-dev
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - vault-secrets-operator
      - argocd
      - default
  view:
    active: context
  featureGates:
    nodeShell: false
  proxy: null
