k9s:
  cluster: arn:aws:eks:us-east-1:555096402965:cluster/eks-production
  namespace:
    active: default
    lockFavorites: false
    favorites:
      - default
  view:
    active: pods default
  featureGates:
    nodeShell: false
  proxy: null
